[phases.setup]
aptPkgs = [
    "libcairo2",
    "libpango-1.0-0",
    "libpangocairo-1.0-0",
    "libgdk-pixbuf2.0-0",
    "libffi-dev",
    "python3-dev",
    "libjpeg-dev",
    "zlib1g-dev",
    "shared-mime-info",
    "poppler-utils"
]
