[phases.setup]
aptPkgs = [
    "libcairo2",
    "libcairo2-dev",
    "libpango-1.0-0",
    "libpangocairo-1.0-0",
    "libgdk-pixbuf2.0-0",
    "libgdk-pixbuf2.0-dev",
    "libglib2.0-0",
    "libglib2.0-dev",
    "libffi-dev",
    "python3-dev",
    "libjpeg-dev",
    "zlib1g-dev",
    "pkg-config",
    "build-essential",
    "shared-mime-info",
    "poppler-utils",
    "gobject-introspection",
    "gir1.2-pango-1.0",
    "gir1.2-gdkpixbuf-2.0"
]
